/* Generated by AN DISI Unibo */ 
package it.unibo.ctxBase;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.qactors.QActorContext;

public class Evh_robotsonar extends AbstractEvh_robotsonar { 
	public Evh_robotsonar(String name, QActorContext myCtx, IOutputEnvView outEnvView, String[] eventIds ) throws Exception {
		super(name, myCtx, outEnvView,eventIds);
  	}
}
