/* Generated by AN DISI Unibo */ 
/*
This code is generated only ONCE
*/
package it.unibo.console;
import alice.tuprolog.NoSolutionException;
import it.unibo.is.interfaces.IActivity;
import it.unibo.is.interfaces.IIntent;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.qactors.QActorContext;

public class Console extends AbstractConsole implements IActivity { 
	private String actionA = "A";
	private String actionNonDavantiS1_1 = "ND_S1_1";
	private String actionS1 = "S1";
	private String actionNonDavantiS1_2 = "ND_S1_2";
	private String actionB = "B";
	
	public Console(String actorId, QActorContext myCtx, IOutputEnvView outEnvView )  throws Exception{
		super(actorId, myCtx, outEnvView);
	}
	
	public int memoSonarEvent(int D, int A){
		outEnvView.addOutput("memo");
		solveGoal("assign(dist,"+D+")");
		solveGoal("assign(angle,"+A+")");
		return 1;
	}
	
	public int inAreaA(){
		int area_a_dist;
		int area_a_angle;
		int dist; 
		int angle;
		try {
			dist = getFromKB("dist");
			angle = getFromKB("angle");
			area_a_dist = getFromKB("area_a_dist");
			area_a_angle = getFromKB("area_a_angle");
			return ((dist < area_a_dist) && (angle < area_a_angle)) ? 1 : 0;
		} catch (NoSolutionException e) {
			outEnvView.addOutput("eccezione:" + e.getMessage());
		}
		return 0;
	}
	
	public int inAreaB(){
		int area_b_dist;
		int area_b_angle;
		int dist; 
		int angle;
		try {
			dist = getFromKB("dist");
			angle = getFromKB("angle");
			area_b_dist = getFromKB("area_b_dist");
			area_b_angle = getFromKB("area_b_angle");
			return ((dist > area_b_dist) && (angle > area_b_angle)) ? 1 : 0;
		} catch (NoSolutionException e) {
			outEnvView.addOutput("eccezione:" + e.getMessage());
		}
		return -1;
	}
	
	public int sonarReached(){
		int angle;
		try {
			angle = getFromKB("angle");
			return (angle > 85 && angle < 95) ? 1 : 0;
		} catch (NoSolutionException e) {
			outEnvView.addOutput("eccezione:" + e.getMessage());
		}
		return 0;
	}
	
	private int getFromKB(String variable) throws NoSolutionException{
		return Integer.parseInt(solveGoal("value(" + variable + ",X)").getVarValue("X").toString());
	}

	public boolean activateGui() throws Exception{
		outEnvView.getEnv().addCmdPanel("btn", new String[]{actionA,actionNonDavantiS1_1,actionS1,actionNonDavantiS1_2,actionB}, this);
		return true;
	}
	
	@Override
	public void execAction(String cmd) {
		try {
			if(cmd.equals(actionA)){
				this.emit("sonar", "p(58,59)");
			}
			else if(cmd.equals(actionNonDavantiS1_1)){
				this.emit("sonar", "p(54,68)");
			}
			else if(cmd.equals(actionS1)){
				this.emit("sonar", "p(50,90)");
			}
			else if(cmd.equals(actionNonDavantiS1_2)){
				this.emit("sonar", "p(51,101)");
			}
			else if(cmd.equals(actionB)){
				this.emit("sonar", "p(158,162)");
			}
		} catch (Exception e) {
			e.printStackTrace();
		} 
	}

	@Override
	public void execAction() {
		// TODO Auto-generated method stub
		
	}

	@Override
	public void execAction(IIntent input) {
		// TODO Auto-generated method stub
		
	}

	@Override
	public String execActionWithAnswer(String cmd) {
		// TODO Auto-generated method stub
		return null;
	}
}
