/* Generated by AN DISI Unibo */ 
/*
This code is generated only ONCE
*/
package it.unibo.console;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.qactors.QActorContext;

public class Console extends AbstractConsole { 
	public Console(String actorId, QActorContext myCtx, IOutputEnvView outEnvView )  throws Exception{
		super(actorId, myCtx, outEnvView);
	}
	
	public void memoSonarEvent(int D, int A){
		solveGoal("assign(d,"+D+")");
		solveGoal("assign(a,"+A+")");
	}
	
	public int checkAreaA(int angle){
		return angle < 70 ? 1 : 0;
	}
	
	public int checkAreaB(int angle){
		return angle > 160 ? 1 : 0;
	}
	
	public int checkSonarReached(int angle){
		return (angle > 85 && angle < 95) ? 1 : 0;
	}
}
