/* Generated by AN DISI Unibo */ 
package it.unibo.ctxBase;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.qactors.QActorContext;

public class Evh_sonar extends AbstractEvh_sonar { 
	public Evh_sonar(String name, QActorContext myCtx, IOutputEnvView outEnvView, String[] eventIds ) throws Exception {
		super(name, myCtx, outEnvView,eventIds);
  	}
}
