/* Generated by AN DISI Unibo */ 
/*
This code is generated only ONCE
*/
package it.unibo.robot;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.qactors.QActorContext;

public class Robot extends AbstractRobot { 
	public Robot(String actorId, QActorContext myCtx, IOutputEnvView outEnvView )  throws Exception{
		super(actorId, myCtx, outEnvView);
	}
	
	public int sendToConsole(int ID){
		try {
			sendMsgMqtt("unibo/mqtt/photowall","photo_wall","robotphoto", "photo_wall("+ID+")");
		} catch (Exception e) {
			outEnvView.addOutput("rotto!");
		}
		return 1;
	}
}
