/* Generated by AN DISI Unibo */ 
/*
This code is generated only ONCE
*/
package it.unibo.console;
import alice.tuprolog.NoSolutionException;
import it.unibo.is.interfaces.IActivity;
import it.unibo.is.interfaces.IIntent;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.qactors.QActorContext;

public class Console extends AbstractConsole implements IActivity {
	private String actionNonDavantiS1_1 = "ND_S1_1";
	private String actionS1 = "S1";
	private String actionNonDavantiS1_2 = "ND_S1_2";
	private String actionNonDavantiS2_1 = "ND_S2_1";
	private String actionS2 = "S2";
	private String actionNonDavantiS2_2 = "ND_S2_2";
	private String actionNonDavantiS3_1 = "ND_S3_1";
	private String actionS3 = "S3";
	
	public Console(String actorId, QActorContext myCtx, IOutputEnvView outEnvView )  throws Exception{
		super(actorId, myCtx, outEnvView);
	}
	
	public int memoSonarEvent(int ID, int D, int A){
		// prendo solo i segnali davanti ai sonar
		if(A > 85 && A < 95){
			solveGoal("assign("+ID+","+D+")");
			outEnvView.addOutput("assign("+ID+","+D+")");
		}else{
			outEnvView.addOutput("valore con angolo errato!");
		}
		return 1;
	}
	
	public int inAreaB(){
		try {
			// controllo se abbiamo raggiunto l'ultimo sonar
			if(getFromKB("nsonars") == getFromKB("sonarreached")) 
				return 1;
		} catch (NoSolutionException e) {
			e.printStackTrace();
		}
		return 0;
	}
	
	public int sendToRadar(int ID, int D){
		int angle = ID*90;
		try {
			sendMsgMqtt("unibo/mqtt/radar","polar","guersant", "p("+D+", "+angle+")");
		} catch (Exception e) {
			outEnvView.addOutput("rotto!");
		}
		return 1;
	}
	
	/*
	 * se la distanza è minore di 80 
	 * stiamo rilevando qualcosa davanti al sonar che non e' il
	 * muro
	 */
	public int sonarReached(){
		int dist;
		int sonarreached;
		try {
			// leggo le distanze e gli angoli riferiti al prossimo sonar da incontrare
			sonarreached = getFromKB("sonarreached");
			sonarreached += 1;
			dist  = getFromKB(""+sonarreached);
			return (dist < 80) ? 1 : 0;
		} catch (NoSolutionException e) {
			return 0;
		}
	}
	
	
	public int expLessThanDMIN(){
		int dmin;
		int sonarreached;
		int nsonars;
		int sum = 0;
		// vado a leggere i vari valori e calcolo la soglia
		try {
			dmin = getFromKB("dmin");
			sonarreached = getFromKB("sonarreached");
			nsonars = getFromKB("nsonars");
			for(int i=sonarreached+2;i<=nsonars;i++){
				sum+=getFromKB(i+"");
			}
			double exp_res = sum/(nsonars-(sonarreached+1));
			outEnvView.addOutput("DEBUG: exp: " +  exp_res);
			return exp_res < dmin ? 1 : 0;
		} catch (NoSolutionException e) {
			return 0;
		} 
	}
	
	private int getFromKB(String variable) throws NoSolutionException{
		return Integer.parseInt(solveGoal("value(" + variable + ",X)").getVarValue("X").toString());
	}

	public boolean activateGui() throws Exception{
		outEnvView.getEnv().addCmdPanel("btn", new String[]{
				actionNonDavantiS1_1,actionS1,actionNonDavantiS1_2,
				actionNonDavantiS2_1,actionS2,actionNonDavantiS2_2,
				actionNonDavantiS3_1,actionS3}, this);
		return true;
	}
	
	@Override
	public void execAction(String cmd) {
		try {
			if(cmd.equals(actionNonDavantiS1_1)){
				this.emit("sonar", "p(1,86,90)");
				this.emit("sonar", "p(2,85,90)");
				this.emit("sonar", "p(3,92,90)");
			}
			else if(cmd.equals(actionS1)){
				this.emit("sonar", "p(1,50,90)");
				this.emit("sonar", "p(2,85,90)");
				this.emit("sonar", "p(3,86,90)");
			}
			else if(cmd.equals(actionNonDavantiS1_2)){
				this.emit("sonar", "p(1,86,90)");
				this.emit("sonar", "p(2,85,90)");
				this.emit("sonar", "p(3,92,90)");
			}
			else if(cmd.equals(actionNonDavantiS2_1)){
				this.emit("sonar", "p(1,86,89)");
				this.emit("sonar", "p(2,86,90)");
				this.emit("sonar", "p(3,86,86)");
			}
			else if(cmd.equals(actionS2)){
				this.emit("sonar", "p(1,86,90)");
				this.emit("sonar", "p(2,50,90)");
				this.emit("sonar", "p(3,86,90)");
			}
			else if(cmd.equals(actionNonDavantiS2_2)){
				this.emit("sonar", "p(1,86,90)");
				this.emit("sonar", "p(2,86,90)");
				this.emit("sonar", "p(3,86,90)");
			}
			else if(cmd.equals(actionNonDavantiS3_1)){
				this.emit("sonar", "p(1,86,90)");
				this.emit("sonar", "p(2,86,90)");
				this.emit("sonar", "p(3,86,90)");
			}
			else if(cmd.equals(actionS3)){
				this.emit("sonar", "p(1,86,90)");
				this.emit("sonar", "p(2,87,90)");
				this.emit("sonar", "p(3,50,90)");
			}
		} catch (Exception e) {
			e.printStackTrace();
		} 
	}

	@Override
	public void execAction() {
		// TODO Auto-generated method stub
		
	}

	@Override
	public void execAction(IIntent input) {
		// TODO Auto-generated method stub
		
	}

	@Override
	public String execActionWithAnswer(String cmd) {
		// TODO Auto-generated method stub
		return null;
	}
	
}
